# docker-compose.override.yml
version:  "3.7"
services:
  php:
    volumes:
      - "./project/class/:/usr/src/app"

  nginx:
    volumes:
      - ./logs/nginx/:/var/log/nginx
      - ./nginx/sites/:/etc/nginx/sites-enabled
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/sites/class.conf:/etc/nginx/conf.d/default.conf'
      - ./project/:/usr/src/app
#      - "./project/class/public:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - ${NGINX_PORT}:80

  phpmyadmin:
    ports:
      - ${ADMINER_PORT}:80